TITLE = "J&P DKP"
CLOSE_BUTTON = "x"
ADD_BUTTON = "+"
SUB_BUTTON = "-"
PLAYER_HEADER = "Player"
AMOUNT_HEADER = "DKP"
DRUID = "Druid"
HUNTER = "Hunter"
MAGE = "Mage"
PRIEST = "Priest"
ROGUE = "Rogue"
SHAMAN = "Shaman"
WARLOCK = "Warlock"
WARRIOR = "Warrior"
INTRO = "----J&P---- Type /jp to open and close the dkp window ----J&P----"
OFFICER_ALT = "Officer Alt"
ALT = "Alt"
ASCENDING = "asc"
DESCENDING = "des"
PLAYER_MAN_DESCRIPTION = "Enter amount:"
QUEUE_BUTTON = "Player benched"
DECAY = "Decay"
UNDO = "Undo last action"
UNDO_ACTION_ADDED = "Added"
UNDO_ACTION_SUBBED = "Subbed"
UNDO_ACTION_DECAY = "Decay"
UNDO_ACTION_RAIDADD = "RaidAdd"
BENCH_TITLE = "Bench"
ALL = "All"
NONE = "None"
TOGGLES = "Show:"
LOG = "Log"
CLEAR_BENCH = "Clear"
SHARE_BENCH = "Share"
LOG_TITLE = "Transaction log"
SETTINGS_TITLE = "Settings"
MANAGEMENT_TITLE = "Management"
LOG_EVENT_HEADER = "Event"
LOG_TIME_HEADER = "Time"
LOG_CHANGE_HEADER = "Change"
LOG_TOTAL_HEADER = "Sum"
LOG_MODIFIER_HEADER = "Modifier"
NEXT = "Next page"
PREVIOUS = "Previous page"
BACK = "Back to raids"
SNAPSHOT = "Create dkp snapshot"
ADDON_PREFIX = "jpdkp"
BENCH_MSG_SHARE = "ShareBench"
SETTINGS = "Settings"

-- XML Frame naming related

PLAYER = "Player"
AMOUNT = "Amount"
PLAYER_MANAGEMENT = "JP_ManagementPlayerManagement"
OUTER_FRAME_LIST_ENTRY = "JP_OuterFrameListEntry"
BACKGROUND = "Background"
LIST_ENTRY = "JP_ListEntry"
CLASS_BUTTON = "JP_ClassButton"
BENCH_ENTRY = "JP_BenchEntry"
MANAGEMENT = "JP_Management"
LOG_FRAME = "JP_LogFrame"

-- Resource paths --
Ony = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-Onyxia"
BWL = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-BlackwingLair"
MC = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-MoltenCore"
AQ = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-TempleofAhnQiraj"
Naxx = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-Naxxramas"

-- Addon messages --
BENCH_MSG_CHANGE_STATE = "ChangeBenchState"
BENCH_MSG_CLEAR = "ClearBench"
LOG_MSG_ENTRY = "LogEntry"