TITLE = "J&P DKP"
CLOSE_BUTTON = "x"
ADD_BUTTON = "+"
SUB_BUTTON = "-"
PLAYER_HEADER = "Player"
AMOUNT_HEADER = "DKP"
BID_HEADER = "Bid"
DRUID = "Druid"
HUNTER = "Hunter"
MAGE = "Mage"
PRIEST = "Priest"
ROGUE = "Rogue"
SHAMAN = "Shaman"
WARLOCK = "Warlock"
WARRIOR = "Warrior"
INTRO = "----J&P---- Type /jp to open and close the dkp window ----J&P----"
OFFICER_ALT = "Officer Alt"
ALT = "Alt"
ASCENDING = "asc"
DESCENDING = "des"
PLAYER_MAN_DESCRIPTION = "Enter amount:"
QUEUE_BUTTON = "Player benched"
DECAY = "Decay"
UNDO = "Undo last action"
UNDO_ACTION_ADDED = "Added"
UNDO_ACTION_SUBBED = "Subbed"
UNDO_ACTION_DECAY = "Decay"
UNDO_ACTION_RAIDADD = "RaidAdd"
BENCH_TITLE = "Bench"
ALL = "All"
NONE = "None"
TOGGLES = "Show:"
LOG = "Log"
CLEAR_BENCH = "Clear bench"
SHARE_BENCH = "Share"
LOG_TITLE = "Transaction log"
INVITE_TITLE = "Invite"
SETTINGS_TITLE = "Settings"
MANAGEMENT_TITLE = "Management"
LOG_EVENT_HEADER = "Event"
LOG_TIME_HEADER = "Time"
LOG_CHANGE_HEADER = "Change"
LOG_TOTAL_HEADER = "Sum"
LOG_MODIFIER_HEADER = "Modifier"
NEXT = "Next page"
PREVIOUS = "Previous page"
BACK = "Back to raids"
SNAPSHOT = "Create dkp snapshot"
ADDON_PREFIX = "jpdkp"
BENCH_MSG_SHARE = "ShareBench"
SETTINGS = "Settings"
SETTING_INFO = "Press enter or escape after edit to save"
BIDDERS_ONLY_SETTING = "Only show bidders in overview"
BIDDERS_ONLY_BOOLEAN_SETTING = "biddersOnlyBoolean"
AUTO_INV_SETTING = "Invite guild members on whisper"
AUTO_INV_BOOLEAN_SETTING = "autoInvBoolean"

-- XML Frame naming related

PLAYER = "Player"
AMOUNT = "Amount"
PLAYER_MANAGEMENT = "JP_ManagementPlayerManagement"
OUTER_FRAME_LIST_ENTRY = "JP_OuterFrameListEntry"
BACKGROUND = "Background"
LIST_ENTRY = "JP_ListEntry"
CLASS_BUTTON = "JP_ClassButton"
BENCH_ENTRY = "JP_BenchEntry"
MANAGEMENT = "JP_Management"
LOG_FRAME = "JP_LogFrame"
DECAY_SETTING_NAME = "DecayPercentage"

-- Resource paths --
ONY_RES = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-Onyxia"
BWL_RES = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-BlackwingLair"
MC_RES = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-MoltenCore"
AQ_RES = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-TempleofAhnQiraj"
NAXX_RES = "Interface\\ENCOUNTERJOURNAL\\UI-EJ-DUNGEONBUTTON-Naxxramas"

-- Raid names --
ONY_NAME = "Onyxia's Lair"
MC_NAME = "Molten Core"
BWL_NAME = "Blackwing Lair"
AQ_NAME = "Temple of Ahn'Qiraj"
NAXX_NAME = "Naxxramas"

-- Addon messages --
BENCH_MSG_ADD = "AddToBench"
BENCH_MSG_REMOVE = "RemoveFromBench"
BENCH_MSG_CLEAR = "ClearBench"
BENCH_MSG_REQUEST = "RequestBenchUpdate"
LOG_MSG_ENTRY = "LogEntry"